import {
  Airplane,
  Briefcase,
  Browser,
  Buildings,
  Calendar,
  Camera,
  Car,
  Certificate,
  ChartLineUp,
  ChatCircleText,
  CheckCircle,
  Clock,
  Cloud,
  Code,
  CreditCard,
  Database,
  DeviceMobile,
  Devices,
  FileText,
  Gear,
  Globe,
  GraduationCap,
  Headset,
  Heart,
  House,
  Image as ImageIcon,
  Layout,
  Lightning,
  LinkSimple,
  Lock,
  Envelope,
  MagnifyingGlass,
  MapTrifold,
  Megaphone,
  Palette,
  PenNib,
  PresentationChart,
  PuzzlePiece,
  Receipt,
  Rocket,
  ShareNetwork,
  ShieldCheck,
  ShoppingCart,
  HardDrives,
  Stack,
  Star,
  Stethoscope,
  Target,
  Tooth,
  Trophy,
  Truck,
  TShirt,
  User,
  UsersThree,
  VideoCamera,
  Wallet,
  AppWindow,
  Wrench,
} from "@phosphor-icons/react/dist/ssr";
import type { IconKey } from "@/lib/pages/types";

export const pageIcons: Record<IconKey, typeof Code> = {
  code: Code,
  layout: Layout,
  browser: Browser,
  cart: ShoppingCart,
  phone: DeviceMobile,
  device: Devices,
  gear: Gear,
  wrench: Wrench,
  shield: ShieldCheck,
  lock: Lock,
  rocket: Rocket,
  chart: ChartLineUp,
  search: MagnifyingGlass,
  megaphone: Megaphone,
  share: ShareNetwork,
  target: Target,
  pen: PenNib,
  palette: Palette,
  image: ImageIcon,
  video: VideoCamera,
  presentation: PresentationChart,
  file: FileText,
  mail: Envelope,
  chat: ChatCircleText,
  users: UsersThree,
  user: User,
  briefcase: Briefcase,
  building: Buildings,
  graduation: GraduationCap,
  server: HardDrives,
  database: Database,
  cloud: Cloud,
  globe: Globe,
  link: LinkSimple,
  card: CreditCard,
  wallet: Wallet,
  receipt: Receipt,
  calendar: Calendar,
  clock: Clock,
  check: CheckCircle,
  star: Star,
  trophy: Trophy,
  certificate: Certificate,
  heart: Heart,
  lightning: Lightning,
  stack: Stack,
  puzzle: PuzzlePiece,
  headset: Headset,
  truck: Truck,
  car: Car,
  camera: Camera,
  house: House,
  tooth: Tooth,
  stethoscope: Stethoscope,
  airplane: Airplane,
  shirt: TShirt,
  window: AppWindow,
  map: MapTrifold,
};
